T2_Apaza_Felix/Models/Distribuidor.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Contracts;


namespace T2_Apaza_Felix.Models
{
    public class Distribuidor
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="El nombre de distribuidor es obligatorio")]
        public string NombreDistribuidor { get; set; }
        [Required(ErrorMessage ="La razón social es obligatoria")]
        public string RazonSocial { get; set; }
        [Required(ErrorMessage ="El teléfono es obligatorio")]
        public int Telefono { get; set; }
        [Required(ErrorMessage ="El año de Inicio de Operación es obligatorio")]
        [Range(1900,3000,ErrorMessage ="El año debe ser entre 1900 y 3000")]
        public int AnioInicioOperacion { get; set; }
        [Required(ErrorMessage ="El contacto es Obligatorio")]
        public string Contacto { get; set; }
    }
}

T2_Apaza_Felix/Models/ErrorViewModel.cs
namespace T2_Apaza_Felix.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

T2_Apaza_Felix/Controllers/DistribuidorController.cs
using Microsoft.AspNetCore.Mvc;

using T2_Apaza_Felix.Datos;
using T2_Apaza_Felix.Models;

namespace T2_Apaza_Felix.Controllers
{
    public class DistribuidorController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DistribuidorController (ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Distribuidor> lista = _db.Distribuidor;
            return View(lista);
        }
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crear(Distribuidor distribuidor)
        {
            if (ModelState.IsValid)
            {
                _db.Distribuidor.Add(distribuidor);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(distribuidor);
        }

        // Get Editar
        public IActionResult Editar(int? Id)
        {
            if (Id==null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.Distribuidor.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        // Post Editar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(Distribuidor distribuidor)
        {
            if (ModelState.IsValid)
            {
                _db.Distribuidor.Update(distribuidor);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(distribuidor);
        }

        // Get Eliminar
        public IActionResult Eliminar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.Distribuidor.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        // Post Eliminar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Eliminar(Distribuidor distribuidor)
        {
            if (distribuidor==null)
            {
                return NotFound();
            }
            _db.Distribuidor.Remove(distribuidor);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

T2_Apaza_Felix/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using T2_Apaza_Felix.Models;

namespace T2_Apaza_Felix.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //Distribuidores Peru
        public IActionResult DisPeru()
        {
            return View();
        }

        //Distribuidores Mundo
        public IActionResult DisMundo()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

T2_Apaza_Felix/Views/Distribuidor/Crear.cshtml
@model T2_Apaza_Felix.Models.Distribuidor;
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear</h1>

<form method="post" asp-action="Crear">
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Nuevo Distribuidor</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreDistribuidor" class="form-label">Nombre Distribuidor</label>
                    <input asp-for="NombreDistribuidor" class="form-control"/>
                    <span asp-validation-for="NombreDistribuidor" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="RazonSocial" class="form-label">Razón Social</label>
                    <input asp-for="RazonSocial" class="form-control" />
                    <span asp-validation-for="RazonSocial" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Telefono" class="form-label">Teléfono</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="AnioInicioOperacion" class="form-label">Año Inicio Operación</label>
                    <input asp-for="AnioInicioOperacion" class="form-control" />
                    <span asp-validation-for="AnioInicioOperacion" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Contacto" class="form-label">Contacto</label>
                    <input asp-for="Contacto" class="form-control" />
                    <span asp-validation-for="Contacto" class="text-danger"></span>
                </div>
            </div>

            <div class="d-grip gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Crear Nuevo</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

T2_Apaza_Felix/Views/Distribuidor/Editar.cshtml
@model T2_Apaza_Felix.Models.Distribuidor;
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<form method="post" asp-action="Editar">
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Editar Distribuidor</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreDistribuidor" class="form-label">Nombre Distribuidor</label>
                    <input asp-for="NombreDistribuidor" class="form-control" />
                    <span asp-validation-for="NombreDistribuidor" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="RazonSocial" class="form-label">Razón Social</label>
                    <input asp-for="RazonSocial" class="form-control" />
                    <span asp-validation-for="RazonSocial" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Telefono" class="form-label">Teléfono</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="AnioInicioOperacion" class="form-label">Año Inicio Operación</label>
                    <input asp-for="AnioInicioOperacion" class="form-control" />
                    <span asp-validation-for="AnioInicioOperacion" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Contacto" class="form-label">Contacto</label>
                    <input asp-for="Contacto" class="form-control" />
                    <span asp-validation-for="Contacto" class="text-danger"></span>
                </div>
            </div>

            <div class="d-grip gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Actualizar</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

T2_Apaza_Felix/Views/Distribuidor/Eliminar.cshtml
@model T2_Apaza_Felix.Models.Distribuidor;
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<form method="post" asp-action="Eliminar">
    <input asp-for="Id" hidden />
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">¿Está seguro de eliminar este distribuidor?</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreDistribuidor" class="form-label">Nombre Distribuidor</label>
                    <input asp-for="NombreDistribuidor" disabled class="form-control" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="RazonSocial" class="form-label">Razón Social</label>
                    <input asp-for="RazonSocial" disabled class="form-control" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Telefono" class="form-label">Teléfono</label>
                    <input asp-for="Telefono" disabled class="form-control" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="AnioInicioOperacion" class="form-label">Año Inicio Operación</label>
                    <input asp-for="AnioInicioOperacion" disabled class="form-control" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Contacto" class="form-label">Contacto</label>
                    <input asp-for="Contacto" disabled class="form-control" />
                </div>
            </div>

            <div class="d-grip gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Eliminar</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

T2_Apaza_Felix/Views/Distribuidor/Index.cshtml
@model IEnumerable<T2_Apaza_Felix.Models.Distribuidor>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div class="container pt-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Lista de Distribuidores</h2>

        </div>
        <div class="col-6">
            <a asp-controller="Distribuidor" asp-action="Crear" class="btn btn-primary">Nuevo distribuidor</a>
        </div>

    </div>

    <br />

    @if(Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Nombre Distribuidor</th>
                    <th>Razón Social</th>
                    <th>Teléfono</th>
                    <th>Año Inicio Operación</th>
                    <th>Contacto</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <th width="20%">@item.NombreDistribuidor</th>
                        <th width="20%">@item.RazonSocial</th>
                        <th width="20%">@item.Telefono</th>
                        <th width="10%">@item.AnioInicioOperacion</th>
                        <th width="20%">@item.Contacto</th>
                        <th>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Distribuidor" asp-action="Editar" asp-Route-Id="@item.Id" class="btn btn-primary mx-2">Editar</a>
                                <a asp-controller="Distribuidor" asp-action="Eliminar" asp-route-Id="@item.Id" class="btn btn-danger mx-2">Eliminar</a>
                            </div>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        
    <p>No hay registros de Distribuidor</p>
    }

</div>


T2_Apaza_Felix/Views/Home/DisMundo.cshtml

@{
    ViewData["Title"] = "DisMundo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Distribuidores Mundo</h1>
<br />
<div class="text-center">
    <h1 class="display-4">Wal-Mart Stores Inc.</h1>
    <p>Corporación multinacional de tiendas de origen estadounidense, que opera cadenas de grandes almacenes de descuento y clubes de almacenes. <a href="https://www.walmart.com/">Más información</a>.</p>
    <img src="https://noticiaslogisticaytransporte.com/wp-content/uploads/2015/06/walmart.png">
</div>
<br />
<br />
<br />
<div class="text-center">
    <h1 class="display-4">Costco Wholesale Corporation</h1>
    <p>Cadena internacional de tiendas de autoservicio con un formato de Club de Precios exclusiva para socios con Membresía vigente. <a href="https://www.costco.com/">Más información</a>.</p>
    <img src="https://peruretail.sfo3.cdn.digitaloceanspaces.com/wp-content/uploads/Costco-Wholesale-scaled.jpg">
</div>
<br />
<br />
<br />
<div class="text-center">
    <h1 class="display-4">The Kroger Co.</h1>
    <p>Empresa minorista estadounidense que opera supermercados y tiendas multidepartamental en todo Estados Unidos. <a href="https://www.thekrogerco.com/">Más información</a>.</p>
    <img src="https://www.seafood.media/attach_fck/kroger_marketplace_southgate_exterior_shot_i(1).jpg">
</div>
<br />
<br />
<br />

T2_Apaza_Felix/Views/Home/DisPeru.cshtml

@{
    ViewData["Title"] = "DisPeru";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Distribuidores Perú</h1>
<br />
<div class="text-center">
    <h1 class="display-4">EFC - Servicio de Importaciones</h1>
    <p>Consolidación de Compras - Somos la empresa peruana líder en la gestión de abastecimiento de suministros industriales. Ofrecemos soluciones de abastecimiento adaptándonos a las necesidades de cada cliente. <a href="https://www.efc.com.pe/">Más información</a>.</p>
    <img src="https://efc.com.pe/wp-content/themes/theme_invitro/images/logo.webp">
</div>
<br />
<br />
<br />
<div class="text-center">
    <h1 class="display-4">Alemar Group - Fabricante de repuestos</h1>
    <p>Distribución de autopartes - Carros, motos o todoterreno. Que la iluminación de tu auto nunca te falte con Luxled. Todo lo que necesitas para equipar tu local o negocio al mejor precio del mercado. Importadora de respuestos. <a href="https://www.alemargroup.com.pe/">Más información</a>.</p>
    <img src="https://media.licdn.com/dms/image/C4D0BAQGehnqAtTkEdA/company-logo_200_200/0/1630510571551/alemar_group_logo?e=1724889600&v=beta&t=e25G-NkgpxXumRTXPjLdfiSmFtYTCac4CYxpcviTTdE">
</div>
<br />
<br />
<br />
<div class="text-center">
    <h1 class="display-4">NS Technology - Suministros de impresión</h1>
    <p>Papel bond, Toners, tintas - Venta y distribución de suministros para impresión, toners, cartuchos, tintas, cajas. de papel bond. En las marcas HP, Epson, Canon, Brother, entre otras. <a href="https://www.nstecnology.com.pe/suministros">Más información</a>.</p>
    <img src="https://www.nstecnology.com.pe/suministros/images/logo.png">
</div>
<br />
<br />
<br />

T2_Apaza_Felix/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenidos</h1>
    <p>Pregunta 1 y 2 de la evaluación T2 de Diseño y Arquitectura de Software</p>
</div>

T2_Apaza_Felix/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - T2_Apaza_Felix</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/T2_Apaza_Felix.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">T2_Apaza_Felix</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Distribuidor" asp-action="Index">Distribuidor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="DisPeru">Distribuidores PER</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="DisMundo">Distribuidores MUN</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - T2_Apaza_Felix - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>